artifact_uri: .//cliicy\0\107ec932ae5b47a98efdbd8e2b2bde17\artifacts
end_time: 1528619353616
entry_point_name: ''
experiment_id: 0
name: Run 1
run_uuid: 107ec932ae5b47a98efdbd8e2b2bde17
source_name: H:/2018_git_task/Demo_MLProject/train/my_train.py
source_type: 4
source_version: 55deea6502e28fa2c92d27c464bfc58e10db4105
start_time: 1528619353165
status: 3
tags: []
user_id: unknown
